
name: TestnBuild

on: 
  push: 
    branches: 
      - master
      
env:
  DOTNET_VERSION: '6.x.x'
    
jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout deploy build
          uses: actions/checkout@v3
          
        - name: Setup dotnet
          uses: actions/setyp-dotnet@v2
          with:
            dotnet-version: ${{env.DOTNET_VERSION}}
            
        - name: Restore nuget
          run: dotnet restore
          
          