name: TestnBuild

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '6.x.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy build
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Restore nuget
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore

      - name: RunTests
        run: dotnet test -c Release --no-restore

      - name: Publish
        run: dotnet publish 0c Release -o ./deploy
      
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          path: ./deploy
      
          