name: TestnBuild

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '6.x.x'

jobs:
  runBenchmark:
    runs-on: ubuntu-latest
    needs: runTests
    steps:
      - name: Checkout deploy build
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      
      - name: Restore nuget
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore
        
      - name: Run benchmark
        run: dotnet ./Benchmark/bin/Release/net6.0/Benchmark.dll -c Release
        
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Benchmarks
          path: ./BenchmarkDotNet.Artifacts/
      
  runTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy build
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Restore nuget
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore

#      - name: RunTests
#        run: dotnet test -c Release --no-restore
  
  buildUpload:
    needs: runTests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy build
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Restore nuget
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: AsyncBehaviours_netstandard2_0
          path: ./AsyncBehaviours/bin/Release/netstandard2.0/AsyncBehaviours.dll
      
          