name: TestnBuild

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '6.x.x'

jobs:
  runBenchmark:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout deploy build
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      
      - name: Run benchmark
        run: dotnet Benchmark/bin/Release/net6.0/Benchmark.dll -c Release
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy build
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Restore nuget
        run: dotnet restore

      - name: Build app
        run: dotnet build -c Release --no-restore

#      - name: RunTests
#        run: dotnet test -c Release --no-restore

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          path: ./AsyncBehaviours/bin/Release/netstandard2.1/AsyncBehaviours.dll
      
          